.MODEL SMALL
.STACK
.DATA
	PROMPT_WORD DB "Enter a word: $"
	SEC_CHAR_MSG DB 0DH, 0AH, "The second character is $"
	PARA_LIST LABEL BYTE
	MAX_LEN DB 20
	ACT_LEN DB ?
	INPUT_DATA DB 20 DUP ("$")
.CODE
MAIN PROC
	MOV AX, @DATA
	MOV DS, AX
	;--PROMPT WORD
	MOV AH, 09H
	LEA DX, PROMPT_WORD
	INT 21H
	;--INPUT STRING
	MOV AH, 0AH
	LEA DX, PARA_LIST
	INT 21H
	;--DISPLAY SECOND CHAR
	MOV AH, 09H
	LEA DX, SEC_CHAR_MSG
	INT 21H
	MOV AH, 02H
	MOV DL, INPUT_DATA[1]
	INT 21H

	MOV AX, 4C00H
	INT 21H
MAIN ENDP
END MAIN
