.MODEL SMALL
.STACK
.DATA
	PROMPT_SECRET_WORD DB "Enter secret word :$"
	PROMPT_ENCRYPT_KEY DB 0DH, 0AH, "Enter encryption key (1-9) : $"
	ENCRYPTED_WORD_MSG DB 0DH, 0AH, "The encryted word is $"
	PARA_LIST LABEL BYTE
	MAX_LEN DB 20
	ACT_LEN DB ?
	INPUT_DATA DB 20 DUP ("$")
	INPUT_KEY DB ?
.CODE
MAIN PROC
	MOV AX, @DATA
	MOV DS, AX
	;--DISPLAY PROMPT SECRECT WORD
	MOV AH, 09H
	LEA DX, PROMPT_SECRET_WORD
	INT 21H
	;--GET USER INPUT (STRING)
	MOV AH, 0AH
	LEA DX, PARA_LIST
	INT 21H
	;-DISPLAY PROMPT KEY
	MOV AH, 09H
	LEA DX, PROMPT_ENCRYPT_KEY
	INT 21H
	;--GET USER INPUT (CHAR)
	MOV AH, 01H
	INT 21H
	MOV INPUT_KEY, AL
	SUB INPUT_KEY, 30H
	;--DISPLAY ENCRYPTED WORD
	MOV AH, 09H
	LEA DX, ENCRYPTED_WORD_MSG
	INT 21H
	MOV CL, ACT_LEN
	MOV SI, 0
	ENCRYPTION:
		MOV AL, INPUT_DATA[SI]
		ADD AL, INPUT_KEY
		MOV AH, 02H
		MOV DL, AL
		INT 21H
		INC SI
	LOOP ENCRYPTION
	
	MOV AX, 4C00H
	INT 21H
MAIN ENDP
END MAIN
