.MODEL SMALL
.STACK 
.DATA
	BOOLEAN_MENU DB "1. x AND y", 0DH, 0AH
				DB "2. x OR y", 0DH, 0AH
				DB "3. NOT x", 0DH, 0AH
				DB "4. x XOR y", 0DH, 0AH
				DB "5. Exit program", 0DH, 0AH
				DB "Please select an option (1-5): $"
	INPUT_MENU DB ?
	PROMPT_X DB 0DH, 0AH, "Please enter x: $"
	PROMPT_Y DB 0DH, 0AH, "Enter value for y (0 or 1): $"
	RESULT_MSG DB 0DH, 0AH, "The result is : $"
    INPUT_X DB ?
    INPUT_Y DB ?
	CONT_MSG DB 0DH, 0AH, "Continue? (Y/N) : $"
	NEWLINE DB 0DH, 0AH, "$"
.CODE
MAIN PROC

    MOV AX, @DATA
    MOV DS, AX
	
	MAIN_MENU:
	;--CLEAR SCREEN
		MOV AH, 06H
		MOV BH, 71H
		MOV CX, 0000H
		MOV DX, 184FH
		INT 10H
	;--SET CURSOR
	MOV AH, 02H
	MOV BH, 00H    ;--PAGE NUMBER
	MOV DX, 0000H  ;--DH = ROW, DL = COLUMN
	INT 10H
	;--NEWLINE
		MOV AH, 09H
		LEA DX, NEWLINE
		INT 21H
	;--DISPLAY BOOLEAN MENU
		MOV AH, 09H
		LEA DX, BOOLEAN_MENU
		INT 21H
	;-GET USER INPUT
		MOV AH, 01H
		INT 21H
		MOV INPUT_MENU, AL
	;--CHECK INPUT MENU
		CMP INPUT_MENU, '5' ;--EXIT IF '5'
		JE EXIT
		CMP INPUT_MENU, '1' ;--EXIT IF '1'
		JE X_AND_Y
	
	;X AND Y
	X_AND_Y:
		;--DISPLAY PROMPT X MESSAGE
		MOV AH, 09H
		LEA DX, PROMPT_X
		INT 21H
		;--GET INPUT X
		MOV AH, 01H
		INT 21H
		MOV INPUT_X, AL
		SUB INPUT_X, 30H
		;--DISPLAY PROMPT_Y MESSAGE
		MOV AH, 09H
		LEA DX, PROMPT_Y
		INT 21H
		;--GET INPUT Y
		MOV AH, 01H
		INT 21H
		MOV INPUT_Y, AL
		SUB INPUT_Y, 30H
		CALL AND_FUNC
		
	CONTINUE:
		;--DISPLAY CONTINUE MESSAGE
		MOV AH, 09H
		LEA DX, CONT_MSG
		INT 21H
		MOV AH, 01H
		INT 21H
		CMP AL, 'N'
		JE EXIT
		CMP AL, 'Y'
		JE MAIN_MENU
		
	EXIT:
		MOV AX, 4C00H
		INT 21H
MAIN ENDP

AND_FUNC PROC
	MOV BL, INPUT_X
	AND BL, INPUT_Y
	MOV AH, 09H
	LEA DX, RESULT_MSG
	INT 21H
	MOV AH, 02H
	MOV DL, BL
	ADD DL, 30H
	INT 21H
	RET
AND_FUNC ENDP
END MAIN
